project:
  type: website
  output-dir: docs

website:
  title: "FengLab"
  favicon: images/favicon.png
  navbar:
    left:
      - href: insights.qmd
        text: Insights
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: upcoming.qmd
        text: Upcoming
      - href: fun.qmd
        text: Fun
      - href: support.qmd
        text: Support
      - href: join.qmd
        text: Join
      - href: contact.qmd
        text: Contact
      - href: zh/index.qmd
        text: 中文版

  page-footer:
    center: "© 2026 FengLab"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
